### ISSUE TITLE
To-do: finish recursion assignment

### ISSUE THREAD

**Issue by ad-auroram** [ad-auroram/Spring-24-projects#1]
- [x] printAllPaths() *prints every root to leaf path in the tree*
- [x] pruneK() *given number k, remove nodes which are not part of a path having a sum greater than or equal to k*
- [x] lca() *return a node that is the closest ancestor of both nodes. a node can be its own ancestor*
- [x] balanceTree() *creates a balanced BST from and unbalanced tree*
- [x] keepRange() *removes nodes with values outside a given range*
- [x] countBST() *returns the number of BSTs present within a BST*

**Comment by ad-auroram** [comment]
Forgot to update this whoops.
Can confirm, all done.
